import { useCallback, useEffect, useState } from 'react'
import { hasCloud, supabase } from './client'
import { ENROLMENT_KEY, type Enrolment } from './sync'
import { loadJSON } from '../platform/storage'
import type { ChildRequest, DeviceRecord, RequestKind, Routine, SafeZone } from '../domain/v2'
export type V2Location={childId:string;latitude:number;longitude:number;accuracyM:number|null;battery:number|null;recordedAt:string}
export type RewardTransaction={id:string;householdId:string;childId:string;source:string;status:string;payload:Record<string,unknown>;createdAt:string|null}
export type V2Dashboard={devices:DeviceRecord[];requests:ChildRequest[];routines:Routine[];safeZones:SafeZone[];locations:V2Location[]}
const empty:V2Dashboard={devices:[],requests:[],routines:[],safeZones:[],locations:[]}
const mapDevice=(r:Record<string,unknown>):DeviceRecord=>({id:String(r.id),householdId:String(r.household_id),childId:r.child_id as string|null,installId:String(r.install_id),platform:String(r.platform),displayName:r.display_name as string|null,enrollmentState:r.enrollment_state as DeviceRecord['enrollmentState'],managementMode:r.management_mode as DeviceRecord['managementMode'],lastSeenAt:r.last_seen_at as string|null})
const mapRequest=(r:Record<string,unknown>):ChildRequest=>({id:String(r.id),householdId:String(r.household_id),childId:String(r.child_id),deviceId:r.device_id as string|null,kind:r.kind as ChildRequest['kind'],payload:(r.payload??{}) as Record<string,unknown>,status:r.status as ChildRequest['status'],requestedAt:String(r.requested_at)})
const mapReward=(r:Record<string,unknown>):RewardTransaction=>({id:String(r.id),householdId:String(r.household_id),childId:String(r.child_id),source:String(r.source??'family'),status:String(r.status??'approved'),payload:(r.payload??{}) as Record<string,unknown>,createdAt:r.created_at==null?null:String(r.created_at)})
export async function loadV2Dashboard(householdId:string):Promise<V2Dashboard>{if(!hasCloud())return empty;const db=supabase();const[{data:devices,error:de},{data:requests,error:re},{data:routines,error:roe},{data:zones,error:ze},{data:locations,error:le}]=await Promise.all([db.from('devices').select('*').eq('household_id',householdId).order('updated_at',{ascending:false}),db.from('child_requests').select('*').eq('household_id',householdId).eq('status','pending').order('requested_at',{ascending:false}).limit(10),db.from('routines').select('*').eq('household_id',householdId).eq('active',true).order('name'),db.from('safe_zones').select('*').eq('household_id',householdId).eq('active',true).order('name'),db.from('device_locations').select('*').order('updated_at',{ascending:false})]);if(de)throw de;if(re)throw re;if(roe)throw roe;if(ze)throw ze;if(le)throw le;return{devices:(devices??[]).map(r=>mapDevice(r as Record<string,unknown>)),requests:(requests??[]).map(r=>mapRequest(r as Record<string,unknown>)),routines:(routines??[]).map(r=>({id:String(r.id),householdId:String(r.household_id),childId:r.child_id as string|null,name:String(r.name),timezone:String(r.timezone),schedule:(r.schedule??{}) as Record<string,unknown>,policyProfileId:r.policy_profile_id as string|null,action:(r.action??{}) as Record<string,unknown>,active:Boolean(r.active)})),safeZones:(zones??[]).map(r=>({id:String(r.id),householdId:String(r.household_id),name:String(r.name),latitude:Number(r.latitude),longitude:Number(r.longitude),radiusM:Number(r.radius_m),active:Boolean(r.active),childIds:(r.child_ids??[]) as string[]})),locations:(locations??[]).map(r=>({childId:String(r.child_id),latitude:Number(r.latitude),longitude:Number(r.longitude),accuracyM:r.accuracy_m==null?null:Number(r.accuracy_m),battery:r.battery==null?null:Number(r.battery),recordedAt:String(r.recorded_at)}))}}
export function useV2Dashboard(householdId?:string){const[data,setData]=useState<V2Dashboard>(empty);const[loading,setLoading]=useState(Boolean(householdId&&hasCloud()));const[error,setError]=useState<string|null>(null);const refresh=useCallback(async()=>{if(!householdId||!hasCloud()){setData(empty);setLoading(false);return}setLoading(true);try{setData(await loadV2Dashboard(householdId));setError(null)}catch(e){setError(e instanceof Error?e.message:'Could not refresh the family dashboard.')}finally{setLoading(false)}},[householdId]);useEffect(()=>{void refresh()},[refresh]);useEffect(()=>{if(!householdId||!hasCloud())return;let timer:number|undefined;const schedule=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void refresh(),250)};const channel=supabase().channel(`nestly-v2-${householdId}`).on('postgres_changes',{event:'*',schema:'public',table:'devices',filter:`household_id=eq.${householdId}`},schedule).on('postgres_changes',{event:'*',schema:'public',table:'child_requests',filter:`household_id=eq.${householdId}`},schedule).on('postgres_changes',{event:'*',schema:'public',table:'routines',filter:`household_id=eq.${householdId}`},schedule).on('postgres_changes',{event:'*',schema:'public',table:'safe_zones',filter:`household_id=eq.${householdId}`},schedule).subscribe();return()=>{window.clearTimeout(timer);void supabase().removeChannel(channel)}},[householdId,refresh]);return{data,loading,error,refresh}}
export async function loadChildRewards():Promise<RewardTransaction[]>{if(!hasCloud())return[];const e=await loadJSON<Enrolment|null>(ENROLMENT_KEY,null);if(!e)return[];const{data,error}=await supabase().from('reward_transactions').select('*').eq('household_id',e.householdId).eq('child_id',e.childId).eq('status','approved').order('created_at',{ascending:false}).limit(30);if(error)throw error;return(data??[]).map(r=>mapReward(r as Record<string,unknown>))}
export function useChildRewards(){const[rewards,setRewards]=useState<RewardTransaction[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const refresh=useCallback(async()=>{setLoading(true);try{setRewards(await loadChildRewards());setError(null)}catch(e){setError(e instanceof Error?e.message:'Could not load rewards.')}finally{setLoading(false)}},[]);useEffect(()=>{void refresh()},[refresh]);return{rewards,loading,error,refresh}}
export async function createChildRequest(input:{kind:RequestKind;payload:Record<string,unknown>;deviceId?:string}):Promise<void>{if(!hasCloud())throw new Error('Cloud service is not configured.');const e=await loadJSON<Enrolment|null>(ENROLMENT_KEY,null);if(!e)throw new Error('This device is not linked to a family yet. Enter the setup code first.');const{error}=await supabase().from('child_requests').insert({household_id:e.householdId,child_id:e.childId,device_id:input.deviceId??null,kind:input.kind,payload:input.payload,status:'pending',requested_at:new Date().toISOString()});if(error)throw error}
export async function resolveChildRequest(request:ChildRequest,approved:boolean):Promise<void>{if(!hasCloud())throw new Error('Cloud service is not configured.');const db=supabase();const{error}=await db.from('child_requests').update({status:approved?'approved':'declined',resolved_at:new Date().toISOString(),resolution:{approved}}).eq('id',request.id).eq('status','pending');if(error)throw error;if(approved&&request.kind==='extra_screen_time'){const minutes=Number(request.payload.minutes??request.payload.screenTimeMinutes??0);if(Number.isFinite(minutes)&&minutes>0){const{error:rewardError}=await db.from('reward_transactions').insert({household_id:request.householdId,child_id:request.childId,source:'request',status:'approved',payload:{screenTimeMinutes:Math.floor(minutes),requestId:request.id}});if(rewardError)throw rewardError}}}
