import { useState } from 'react'
import { useDevice } from '../platform/device'
import { useStore } from '../app/store'
import { createChildRequest } from '../cloud/v2'
import type { RequestKind } from '../domain/v2'

function Shell({ title, subtitle, children }: { title:string; subtitle:string; children:React.ReactNode }) { const {go}=useStore(); return <div className="flex h-full flex-col overflow-y-auto px-[22px] pb-8 pt-7"><button onClick={()=>go('childHome')} className="mb-5 w-fit text-xs font-bold text-brand">← Back</button><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-xs text-body">{subtitle}</p><div className="mt-6 space-y-3">{children}</div></div> }
export function ChildRoutinesV2(){const{agent}=useDevice();return <Shell title="My routines" subtitle="See what is happening on your device."><div className="rounded-2xl bg-tint p-4"><b className="text-sm">{agent?.activeScenario?.name??'No routine active'}</b><p className="mt-1 text-xs text-body">{agent?.activeScenario?`Ends in ${agent.unlocksInMin??0} minutes.`:'Your normal device access is available.'}</p></div><div className="rounded-2xl bg-cream p-4 text-xs text-body">When a routine is active, emergency communication should remain available.</div></Shell>}
export function ChildRequestsV2(){const{deviceId}=useDevice();const[kind,setKind]=useState<RequestKind>('extra_screen_time');const[minutes,setMinutes]=useState('30');const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const submit=async()=>{setBusy(true);setMessage(null);try{const payload=kind==='extra_screen_time'?{minutes:Math.max(1,Math.min(240,Number(minutes)||30))}:{};await createChildRequest({kind,payload,deviceId});setMessage('Request sent to your parent.');}catch(e){setMessage(e instanceof Error?e.message:'Could not send your request.')}finally{setBusy(false)}};return <Shell title="My requests" subtitle="Ask your parent for help or more access."><div className="rounded-2xl bg-cream p-4"><label className="text-[11px] font-bold text-body">WHAT DO YOU NEED?</label><select value={kind} onChange={e=>setKind(e.target.value as RequestKind)} className="mt-2 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm"><option value="extra_screen_time">More screen time</option><option value="app_access">Use an app</option><option value="temporary_unlock">Temporary unlock</option><option value="routine_exception">Routine exception</option></select>{kind==='extra_screen_time'&&<><label className="mt-4 block text-[11px] font-bold text-body">MINUTES</label><input value={minutes} onChange={e=>setMinutes(e.target.value)} inputMode="numeric" className="mt-2 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm" /></>}<button disabled={busy} onClick={()=>void submit()} className="mt-4 w-full rounded-xl bg-brand px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'Sending…':'Send request'}</button></div>{message&&<div className="rounded-xl bg-tint p-3 text-xs text-tealInk">{message}</div>}<div className="rounded-2xl bg-cream p-4 text-xs text-body">Your parent can approve or decline requests from their Nestly Control Centre.</div></Shell>}
export function ChildRewardsV2(){return <Shell title="My rewards" subtitle="Keep track of the good things you earn."><div className="rounded-2xl bg-tint p-5"><div className="text-xs text-body">CURRENT REWARDS</div><div className="mt-2 text-xl font-bold">Approved rewards appear here</div><p className="mt-2 text-xs text-body">Extra screen time and other rewards will be shown when your parent approves them.</p></div></Shell>}
